theme: jekyll-theme-slate
title: "Multi-View Stereo by Temporal Nonparametric Fusion"
description: "<a href='#'>Yuxin Hou</a>, <a href='https://users.aalto.fi/~kannalj1/'>Juho Kannala</a>, and <a href='http://arno.solin.fi'>Arno Solin</a>"
